apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${application.name}
  labels:
    app: ${application.name}
spec:
  selector:
    matchLabels:
      app: ${application.name}
  template:
    metadata:
      labels:
        app: ${application.name}
    spec:
      enableServiceLinks: false
      containers:
      - name: ${application.name}
        image: ${application.name}:${application.version}
        ports:
        - name: http
          containerPort: ${server.port}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
        startupProbe:
          httpGet:
            path: ${management.endpoints.web.basePath}/health
            port: ${management.server.port}
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: ${management.endpoints.web.basePath}/health/liveness
            port: ${management.server.port}
        readinessProbe:
          httpGet:
            path: ${management.endpoints.web.basePath}/health/readiness
            port: ${management.server.port}
