configMapGenerator:
- name: ${application.name}-config-properties
  envs:
  - config.properties
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
resources:
- deployment.yaml
- service.yaml
patches:
- path: config-from-volume.yaml
#- path: config-from-env.yaml