apiVersion: v1
kind: Service
metadata:
  name: ${application.name}
  labels:
    app: ${application.name}
spec:
  selector:
    app: ${application.name}
  ports:
    - port: ${server.port}
      targetPort: ${server.port}
  type: LoadBalancer