spring.application.name: ${name}

spring.datasource:
  url: jdbc:mysql:///${spring.application.name}
  username: root
  password:
  hikari:
    maximumPoolSize: 10
    minimumIdle: 2
    idleTimeout: 600000
    connectionTimeout: 30000
    maxLifetime: 1800000

spring.jpa:
  hibernate.ddl-auto: update

spring.jackson:
  default-property-inclusion: non_null

management.endpoints.web.exposure.include: health
springfox.documentation.enabled: false

---
spring.config.activate.on-profile: dev
springfox.documentation.enabled: true
management.endpoints.web.exposure.include: "*"
spring.jackson.serialization.indent_output: true
