spring.application.name: ${name}

server:
  shutdown: graceful

spring.datasource:
  url: jdbc:mysql:///${spring.application.name}?createDatabaseIfNotExist=true
  username: root
  password:
  hikari:
    maximumPoolSize: 10
    minimumIdle: 2
    idleTimeout: 600000
    connectionTimeout: 30000
    maxLifetime: 1800000

spring.jpa:
  open-in-view: false
  hibernate.use-new-id-generator-mappings: false

spring.jackson:
  default-property-inclusion: non_null

logging.group.sql: org.hibernate.SQL,org.hibernate.type.descriptor.sql.BasicBinder,org.springframework.jdbc.core

management.endpoints.web.exposure.include: health
springfox.documentation.enabled: false

---
spring:
  config.activate.on-profile: dev|test
  devtools.livereload.enabled: false
  jackson.serialization.indent_output: true
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      hbm2ddl.default_constraint_mode: NO_CONSTRAINT
springfox.documentation.enabled: true
management.endpoints.web.exposure.include: "*"
logging.level.sql: TRACE

