spring.application.name: demo

server:
  shutdown: graceful

spring.datasource:
  url: jdbc:mysql:///${spring.application.name}?createDatabaseIfNotExist=true
  username: root
  password:
  hikari:
    maximumPoolSize: 10
    minimumIdle: 2
    idleTimeout: 600000
    connectionTimeout: 30000
    maxLifetime: 1800000

spring.jpa:
  open-in-view: false
  hibernate.use-new-id-generator-mappings: false

spring.jackson:
  default-property-inclusion: non_null

logging:
  config: classpath:log4j2.xml
  group.SQL: org.hibernate.SQL,org.hibernate.type.descriptor.sql.BasicBinder,org.springframework.jdbc.core

management.endpoints.web.exposure.include: health
springfox.documentation.enabled: false

---
spring:
  config.activate.on-profile: dev|test
  devtools.livereload.enabled: false
  jackson.serialization.indent_output: true
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      hbm2ddl.default_constraint_mode: NO_CONSTRAINT
springfox.documentation.enabled: true
management.endpoints.web.exposure.include: "*"
logging:
  level.SQL: TRACE

---
spring:
  config.activate.on-profile: prod
logging:
  config: classpath:log4j2-with-kafka.xml

