spring.application.name: demo

server:
  shutdown: graceful

spring.datasource:
  url: jdbc:mysql:///${spring.application.name}?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai&autoReconnectForPools=true&useUnicode=true&useServerPrepStmts=true&cachePrepStmts=true&tinyInt1isBit=false&socketTimeout=60000&sslMode=DISABLED&allowPublicKeyRetrieval=true
  username: root
  password:
  hikari:
    maximumPoolSize: 100
    minimumIdle: 5
    idleTimeout: 1800000
    connectionTimeout: 10000
    maxLifetime: 7200000
    autoCommit: false

spring.jpa:
  open-in-view: false
  hibernate.use-new-id-generator-mappings: false

spring.jackson:
  default-property-inclusion: non_null

logging:
  config: classpath:log4j2.xml
  group.SQL: org.hibernate.SQL,org.hibernate.type.descriptor.sql.BasicBinder,org.springframework.jdbc.core

management.endpoints.web.exposure.include: health
management.metrics.export.influx:
  enabled: false
  db: metrics
  step: 10s
springfox.documentation.enabled: false

opentracing.jaeger:
  enabled: false
  enable-w3c-propagation: true
  http-sender.url: http://localhost:14268/api/traces
  const-sampler.decision: true
  log-spans: false

---
spring:
  config.activate.on-profile: dev|test
  devtools.livereload.enabled: false
  jackson.serialization.indent_output: true
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      hbm2ddl.default_constraint_mode: NO_CONSTRAINT
springfox.documentation.enabled: true
management.endpoints.web.exposure.include: "*"
logging:
  level.SQL: TRACE

---
spring:
  config.activate.on-profile: prod
logging:
  config: classpath:log4j2-with-kafka.xml
management.metrics.export.influx.enabled: true
opentracing.jaeger:
  enabled: true
  const-sampler.decision: false
  probabilistic-sampler.sampling-rate: 0.01

